import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export function middleware(request: NextRequest) {
    // Read the session cookie generated by our AuthContext
    const sessionCookie = request.cookies.get('__session');
    const session = sessionCookie?.value;

    let isValid = false;

    if (session) {
        try {
            // Lightweight JWT decoding (base64 payload)
            const payloadBase64 = session.split('.')[1];
            if (payloadBase64) {
                // Decode base64url to JSON string
                const payloadString = atob(payloadBase64.replace(/-/g, '+').replace(/_/g, '/'));
                const payload = JSON.parse(payloadString);

                // Check if the token is expired
                const currentTime = Math.floor(Date.now() / 1000);
                if (payload.exp && payload.exp > currentTime) {
                    isValid = true;
                }
            }
        } catch (error) {
            console.error('Error decoding JWT in middleware:', error);
        }
    }

    if (!isValid) {
        // Clear the invalid or expired cookie
        const response = NextResponse.redirect(
            new URL(request.nextUrl.pathname.startsWith('/student-dashboard') ? '/student-login' : '/login', request.url)
        );
        response.cookies.delete('__session');
        return response;
    }

    // Pass through if authenticated
    return NextResponse.next();
}

// Ensure the middleware is only invoked for protected routes
export const config = {
    matcher: ['/dashboard/:path*', '/student-dashboard/:path*'],
};
